### ISSUE TITLE
Error running local transform; Cannot import Phrase

### ISSUE THREAD

**Issue by Coding4Sec** [INTERPOL-Innovation-Centre/GraphSense-Maltego-transform#7]
Hi. When running local transform *todetails* on a BTC-address, Python3 returned w/ exit code 1. Message:

Traceback (most recent call last):
  File "/Users/crg/Git/GraphSense-Maltego-transform/project.py", line 13, in <module>
    register_transform_classes(transforms)
  File "/usr/local/lib/python3.10/site-packages/maltego_trx/registry.py", line 40, in register_transform_classes
    module = __import__(modname, fromlist="dummy")
  File "/Users/crg/Git/GraphSense-Maltego-transform/transforms/ToCluster.py", line 6, in <module>
    from api.utils import create_entity_with_details, get_currency_from_entity_details, get_address_details
  File "/Users/crg/Git/GraphSense-Maltego-transform/api/utils.py", line 1, in <module>
    from maltego_trx.maltego import MaltegoEntity, MaltegoTransform, Phrase
ImportError: cannot import name 'Phrase' from 'maltego_trx.maltego' (/usr/local/lib/python3.10/site-packages/maltego_trx/maltego.py)

Within a python3-Console import of MaltegoEntity und MaltegoTransform is ok: At least there is no error message, see below

Python 3.10.7 (main, Oct 11 2022, 07:24:09) [Clang 10.0.1 (clang-1001.0.46.4)] on darwin

Type "help", "copyright", "credits" or "license" for more information.

>>> from maltego_trx.maltego import Phrase

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

ImportError: cannot import name 'Phrase' from 'maltego_trx.maltego' (/usr/local/lib/python3.10/site-packages/maltego_trx/maltego.py)

>>> from maltego_trx.maltego import MaltegoEntity

>>> from maltego_trx.maltego import MaltegoTransform

>>> 

Any idea how to fix this error?

(Mac, Python3.10.7), pip3, all updated according to installation manual in this repo

Best, Rick

**Comment by behas** [comment]
Could be a REST interface version conflict. Please make sure to connect to https://api.ikna.io, which hosts the most recent GraphSense release.

@nkoorty plz check and confirm.

**Comment by Coding4Sec** [comment]
Changed host to [https://api.ikna.io/](url) - no effect. 

Does it require an api key related to [ikna.io](url) ?

**Comment by behas** [comment]
Yes, API keys are not compatible. Please request a new one at: https://ikna.io <https://ikna.io/>

**Comment by Coding4Sec** [comment]
[ikna.io](url) as  host and related api key will do the trick. graphsense-python now works and example scripts do the job. Maltego transform still break with error ".. cannot import Phrase."

**Comment by VinceICPO** [comment]
Hi Rick,

"Maltego.Phrase" isn't required, sorry we had left that import call here.
It is strange however that I cannot reproduce this on my machine.
Regardless, the import call is now removed, sorry for the inconvenience.

Best,
Vincent
